### ISSUE TITLE
Variable Substitution

### ISSUE THREAD

**Issue by Hirtol** [OxiDD/oxidd#10]
Hi, I'm trying to implement a symbolic solver using `oxidd`, but this requires some variable substitution here and there. For example, if we have the following:
```rust
// Create two sets of `n_variables` (say 2)
let variables = manager
            .with_manager_exclusive(|man| (0..n_variables).flat_map(|x| BDDFunction::new_var(man)).collect_vec());
let variables_prime = manager
            .with_manager_exclusive(|man| (0..n_variables).flat_map(|x| BDDFunction::new_var(man)).collect_vec());

let bdd_expr = variables[0].and(&variables[1]);

// Ideal API, replace variables[0] with variables_prime[0], etc.
let substituted_expr = bdd_expr.substitute(&variables, &variables_prime);
```

Is there any way at the moment to replace the variable references from `bdd_expr` to `variables_prime[0]` and `variables_prime[1]` instead? In essence cloning the structure of the existing BDD nodes, but positioned on the 'lower' levels.
An approximation seems to be possible by using `Level::swap`, but this swaps all nodes of that level, not just `bdd_expr`'s nodes.

**Comment by nhusung** [comment]
Hi and thank you for the request. If I understand it correctly, the `substitute` method you desire corresponds to BuDDy’s `bdd_veccompose()` and CUDD’s `Cudd_bddVectorCompose()`. Such an operation is not implemented yet, but I’m willing to implement it (should not take long).

**Comment by Hirtol** [comment]
Thanks for the consideration! I was initially thinking of [Cudd_bddSwapVariables()](https://add-lib.scce.info/assets/doxygen-cudd-documentation/cuddCompose_8c.html#a2ab6b6123e102f9b0b61c9d2961f707e) (or [bdd_replace()](https://buddy.sourceforge.net/manual/group__operator_g1515a140796e76786279ba415f2542c9.html#g1515a140796e76786279ba415f2542c9)), but a `veccompose()` equivalent seems like a better, and more general, fit.
