### ISSUE TITLE
Missing BDDFunction level method (Python)

### ISSUE THREAD

**Issue by marnikdenouden** [OxiDD/oxidd#24]
The BDDFunction class is missing the `level()` method in the python version of OxiDD, while there is a [level method on the docs]. It would be great to actually have access to this functionality with python as it is an useful method to have.

[level method on the docs]: https://oxidd.net/api/python/dev/api/oxidd.bdd.html#oxidd.bdd.BDDFunction.level

**Comment by nhusung** [comment]
Which OxiDD version are you using? The method has been added in OxiDD 0.8, which was released only this week.

**Comment by Doodshoofdaapje** [comment]
Thanks for the reply! We installed oxidd last week and missed the update, got it working now with the new version
